<a href="https://colab.research.google.com/github/ferdousejannatul24-cyber/ML_Lab01_128_jannatulferdouse/blob/notebooks/ML_Lab01_128_jannatulferdouse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Activity A — Meet the Notebook
# LAB 1: Welcome to Machine Learning
# Student name: Jannatul Ferdouse
# Student ID: 20245103128
print("Hello, future ML detective!")
print("Rule 1: The computer is literal, not rude.")

Hello, future ML detective!
Rule 1: The computer is literal, not rude.

In [3]:
#Activity B — NumPy: The Array Gym
import numpy as np
np.random.seed(42)
marks = np.array([55, 72, 48, 90, 66, 81])
print('Marks:', marks)
print('Mean:', marks.mean())
print('Highest:', marks.max())
print('Passed:', marks[marks >= 50])

Marks: [55 72 48 90 66 81]
Mean: 68.66666666666667
Highest: 90
Passed: [55 72 90 66 81]

In [4]:
#12. Find the minimum mark and standard deviation.
#13. Add 5 bonus marks to every student without changing the original array.
#14. Count how many students passed.
#15. Create a 2 × 3 matrix from the marks.
import numpy as np

np.random.seed(42)
marks = np.array([55, 72, 48, 90, 66, 81])

print('Marks:', marks)
print('Mean:', marks.mean())
print('Highest:', marks.max())
print('Passed:', marks[marks >= 50])

print('Minimum:', marks.min())
print('Standard Deviation:', marks.std())

bonus_marks = marks + 5
print('Marks with Bonus:', bonus_marks)
print('Original Marks:', marks)

passed_count = np.sum(marks >= 50)
print('Number of Passed Students:', passed_count)

matrix = marks.reshape(2, 3)
print('2 × 3 Matrix:')
print(matrix)

Marks: [55 72 48 90 66 81]
Mean: 68.66666666666667
Highest: 90
Passed: [55 72 90 66 81]
Minimum: 48
Standard Deviation: 14.372040758206733
Marks with Bonus: [60 77 53 95 71 86]
Original Marks: [55 72 48 90 66 81]
Number of Passed Students: 5
2 × 3 Matrix:
[[55 72 48]
 [90 66 81]]

In [5]:
#Activity C — Pandas: The Dataframe Detective
import pandas as pd
data = {
'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
'study_hours': [2, 5, 1, 7, 3, 6],
'sleep_hours': [8, 6, 9, 5, 7, 6],
'attendance': [70, 88, 55, 95, 75, 91],
'snacks': [3, 2, 5, 1, 4, 2],
'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)
display(df)
print(df.info())
print(df.describe())

  student  study_hours  sleep_hours  attendance  snacks passed
0    Asha            2            8          70       3    Yes
1    Babu            5            6          88       2    Yes
2  Chayan            1            9          55       5     No
3    Dipa            7            5          95       1    Yes
4    Emon            3            7          75       4     No
5   Farah            6            6          91       2    Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student      6 non-null      object
 1   study_hours  6 non-null      int64
 2   sleep_hours  6 non-null      int64
 3   attendance   6 non-null      int64
 4   snacks       6 non-null      int64
 5   passed       6 non-null      object
dtypes: int64(4), object(2)
memory usage: 420.0+ bytes
None
       study_hours  sleep_hours  attendance    snacks
count     6.000000     6.000000    6.000000  6.000000
mean      4.000000     6.833333   79.000000  2.833333
std       2.366432     1.471960   15.192103  1.471960
min       1.000000     5.000000   55.000000  1.000000
25%       2.250000     6.000000   71.250000  2.000000
50%       4.000000     6.500000   81.500000  2.500000
75%       5.750000     7.750000   90.250000  3.750000
max       7.000000     9.000000   95.000000  5.000000

In [6]:
#16. Which columns are features? Which column is the label?
#17. How many samples and columns are present?
#18. Filter students with attendance of at least 80.
#19. Calculate average study hours for students who passed.
#20. Sort the DataFrame by attendance in descending order.
#21. Does this tiny dataset prove that snack purchases cause failure? Explain why or why not.
import pandas as pd

data = {
    'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
    'study_hours': [2, 5, 1, 7, 3, 6],
    'sleep_hours': [8, 6, 9, 5, 7, 6],
    'attendance': [70, 88, 55, 95, 75, 91],
    'snacks': [3, 2, 5, 1, 4, 2],
    'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
display(df)
print(df.info())
print(df.describe())

print("Features:", ['study_hours', 'sleep_hours', 'attendance', 'snacks'])
print("Label:", 'passed')

print("Samples:", df.shape[0])
print("Columns:", df.shape[1])

print(df[df['attendance'] >= 80])

print("Average study hours for passed students:", df[df['passed'] == 'Yes']['study_hours'].mean())

print(df.sort_values(by='attendance', ascending=False))

print("No, this tiny dataset does not prove that snack purchases cause failure.")

  student  study_hours  sleep_hours  attendance  snacks passed
0    Asha            2            8          70       3    Yes
1    Babu            5            6          88       2    Yes
2  Chayan            1            9          55       5     No
3    Dipa            7            5          95       1    Yes
4    Emon            3            7          75       4     No
5   Farah            6            6          91       2    Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student      6 non-null      object
 1   study_hours  6 non-null      int64
 2   sleep_hours  6 non-null      int64
 3   attendance   6 non-null      int64
 4   snacks       6 non-null      int64
 5   passed       6 non-null      object
dtypes: int64(4), object(2)
memory usage: 420.0+ bytes
None
       study_hours  sleep_hours  attendance    snacks
count     6.000000     6.000000    6.000000  6.000000
mean      4.000000     6.833333   79.000000  2.833333
std       2.366432     1.471960   15.192103  1.471960
min       1.000000     5.000000   55.000000  1.000000
25%       2.250000     6.000000   71.250000  2.000000
50%       4.000000     6.500000   81.500000  2.500000
75%       5.750000     7.750000   90.250000  3.750000
max       7.000000     9.000000   95.000000  5.000000
Features: ['study_hours', 'sleep_hours', 'attendance', 'snacks']
Label: passed
Samples: 6
Columns: 6
  student  study_hours  sleep_hours  attendance  snacks passed
1    Babu            5            6          88       2    Yes
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
Average study hours for passed students: 5.0
  student  study_hours  sleep_hours  attendance  snacks passed
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
1    Babu            5            6          88       2    Yes
4    Emon            3            7          75       4     No
0    Asha            2            8          70       3    Yes
2  Chayan            1            9          55       5     No
No, this tiny dataset does not prove that snack purchases cause failure.

In [7]:
#Activity D — Reproducibility Experiment
import random
import numpy as np

def generate_scores(use_seed):
    if use_seed:
        random.seed(42)
        np.random.seed(42)
    return np.random.randint(40, 101, size=5)

print('Seeded run 1:', generate_scores(True))
print('Seeded run 2:', generate_scores(True))
print('Unseeded run 1:', generate_scores(False))
print('Unseeded run 2:', generate_scores(False))

Seeded run 1: [78 91 68 54 82]
Seeded run 2: [78 91 68 54 82]
Unseeded run 1: [ 47 100  60  78  97]
Unseeded run 2: [58 62 50 50 63]

In [8]:
#Run the cell twice. Record which outputs remain identical. Then explain: if two groups claim different
#accuracies because they used different random splits, can we fairly compare their models?
import random
import numpy as np

def generate_scores(use_seed):
    if use_seed:
        random.seed(42)
        np.random.seed(42)
        return np.random.randint(40, 101, size=5)
    return np.random.randint(40, 101, size=5)

seeded_run_1 = generate_scores(True)
seeded_run_2 = generate_scores(True)
unseeded_run_1 = generate_scores(False)
unseeded_run_2 = generate_scores(False)

print('Seeded run 1:', seeded_run_1)
print('Seeded run 2:', seeded_run_2)
print('Unseeded run 1:', unseeded_run_1)
print('Unseeded run 2:', unseeded_run_2)

print('Seeded outputs identical:', np.array_equal(seeded_run_1, seeded_run_2))
print('Unseeded outputs identical:', np.array_equal(unseeded_run_1, unseeded_run_2))

print('Models using different random splits cannot be fairly compared directly.')
print('They should use the same random split or the same fixed random seed.')

Seeded run 1: [78 91 68 54 82]
Seeded run 2: [78 91 68 54 82]
Unseeded run 1: [ 47 100  60  78  97]
Unseeded run 2: [58 62 50 50 63]
Seeded outputs identical: True
Unseeded outputs identical: False
Models using different random splits cannot be fairly compared directly.
They should use the same random split or the same fixed random seed.